name: CheckHomework

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      - name: Echo week folder
        run: echo ${BRANCH_NAME} sed -E 's/.*w(eek)?[-_]?([0-9]).*/Week\2/gi'
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
