name: CheckHomework

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - run: echo ${BRANCH_NAME} | grep -P -q '/w(?:eek)?[-_]?(\d{1})/'
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
